Add checks for architectures.
NOTE: It seems like x86_64 is the only architecture supported
everywhere. Nvidia seems to support arm64 in *some* cases, but not a
lot. Should we only support x86_64, then?

diff --git a/providers/gpgpu/tools/gpu-setup b/providers/gpgpu/tools/gpu-setup
--- a/providers/gpgpu/tools/gpu-setup
+++ b/providers/gpgpu/tools/gpu-setup
@@ -44,13 +44,29 @@ echo "*  Adding nVidia package repository"
 
 OSRELEASE=ubuntu`lsb_release -r | cut -f2 |sed -e 's/\.//'`
 ARCH=`uname -m`
-if [[ "$ARCH" =~ "aarch64" ]]; then
-    ARCH="arm64"
-fi
+case $ARCH in
+    arm)
+        ;&
+    aarch64_be)
+        ;&
+    aarch64)
+        ARCH="arm64"
+        ;;
+    x86_64)
+        ;;
+    *)
+        echo "ERROR: Unsupported architecture $ARCH"
+        exit 1
+        ;;
+esac
 REPO_URL="https://developer.download.nvidia.com/compute/cuda/repos/$OSRELEASE/$ARCH"
 
 # Import and verify cuda gpg key
 wget -O cuda-archive-keyring.gpg "$REPO_URL/3bf863cc.pub"
+if [[ $? -eq 8 ]] ; then
+    echo "ERROR: wget failed. $OSRELEASE/$ARCH not supported?"
+    exit 1
+fi
 gpg --no-default-keyring --keyring ./temp-keyring.gpg \
     --import cuda-archive-keyring.gpg
 gpg --no-default-keyring --keyring ./temp-keyring.gpg \
