semantics

diff --git a/providers/base/jobs/miscellanea.txt.in b/providers/base/jobs/miscellanea.txt.in
--- a/providers/base/jobs/miscellanea.txt.in
+++ b/providers/base/jobs/miscellanea.txt.in
@@ -179,7 +179,7 @@ command:
  if [ -s /etc/installed-by-maas ]; then 
    cat /etc/installed-by-maas
  else
-   echo "MAAS VERSION NOT FOUND" >> /dev/stderr
+   echo "MAAS VERSION NOT FOUND" >&2
    false
  fi
 _description: If system was installed via MAAS from a cert server, the MAAS version used should be contained in /etc/installed-by-maas
