providers:checkbox: sed -e 's/CHECKBOX_DATA/PLAINBOX_SESSION_SHARE/g' -i *.txt.in
The CHECKBOX_DATA environment variable is the old spelling of
PLAINBOX_SESSION_SHARE.

Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>

diff --git a/providers/base/jobs/stress.txt.in b/providers/base/jobs/stress.txt.in
--- a/providers/base/jobs/stress.txt.in
+++ b/providers/base/jobs/stress.txt.in
@@ -15,15 +15,15 @@ depends:
 requires:
  sleep.disk == 'supported'
  rtc.state == 'supported'
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 user: root
 command:
  if type -P fwts >/dev/null; then
   echo "Calling fwts"
-  fwts_test -l $CHECKBOX_DATA/hibernate_30_cycles -f none -s s4 --s4-device-check --s4-device-check-delay=45 --s4-sleep-delay=120 --s4-multiple=30
+  fwts_test -l $PLAINBOX_SESSION_SHARE/hibernate_30_cycles -f none -s s4 --s4-device-check --s4-device-check-delay=45 --s4-sleep-delay=120 --s4-multiple=30
  else
   echo "Calling sleep_test"
-  set -o pipefail; sleep_test -s disk -i 30 -w 120 | tee $CHECKBOX_DATA/hibernate_30_cycles.log
+  set -o pipefail; sleep_test -s disk -i 30 -w 120 | tee $PLAINBOX_SESSION_SHARE/hibernate_30_cycles.log
  fi
 _description:
  PURPOSE:
@@ -31,13 +31,13 @@ _description:
 
 plugin: shell
 id: power-management/hibernate-30-cycles-log-check
-command: [ -e $CHECKBOX_DATA/hibernate_30_cycles.log ] && sleep_test_log_check -v s4 $CHECKBOX_DATA/hibernate_30_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/hibernate_30_cycles.log ] && sleep_test_log_check -v s4 $PLAINBOX_SESSION_SHARE/hibernate_30_cycles.log
 _description:
  Automated check of the 30 cycle hibernate log for errors detected by fwts.
 
 plugin: attachment
 id: power-management/hibernate-30-cycle-log-attach
-command: [ -e $CHECKBOX_DATA/hibernate_30_cycles.log ] && cat $CHECKBOX_DATA/hibernate_30_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/hibernate_30_cycles.log ] && cat $PLAINBOX_SESSION_SHARE/hibernate_30_cycles.log
 _description:
  Attaches the log from the 30 cycle Hibernate/Resume test if it exists
 
@@ -46,15 +46,15 @@ id: power-management/suspend_30_cycles
 depends:
  power-management/rtc
  suspend/suspend_advanced
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 user: root
 command:
  if type -P fwts >/dev/null; then
   echo "Calling fwts"
-  set -o pipefail; fwts_test -l $CHECKBOX_DATA/suspend_30_cycles -f none -s s3 --s3-device-check --s3-device-check-delay=45 --s3-sleep-delay=30 --s3-multiple=30 | tee $CHECKBOX_DATA/suspend_30_cycles_times.log
+  set -o pipefail; fwts_test -l $PLAINBOX_SESSION_SHARE/suspend_30_cycles -f none -s s3 --s3-device-check --s3-device-check-delay=45 --s3-sleep-delay=30 --s3-multiple=30 | tee $PLAINBOX_SESSION_SHARE/suspend_30_cycles_times.log
  else
   echo "Calling sleep_test"
-  set -o pipefail; sleep_test -p -s mem -i 30 | tee $CHECKBOX_DATA/suspend_30_cycles.log
+  set -o pipefail; sleep_test -p -s mem -i 30 | tee $PLAINBOX_SESSION_SHARE/suspend_30_cycles.log
  fi
 _description:
  PURPOSE:
@@ -63,36 +63,36 @@ _description:
 plugin: shell
 id: power-management/suspend-30-cycles-log-check
 depends: power-management/suspend_30_cycles
-command: [ -e $CHECKBOX_DATA/suspend_30_cycles.log ] && sleep_test_log_check -v s3 $CHECKBOX_DATA/suspend_30_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/suspend_30_cycles.log ] && sleep_test_log_check -v s3 $PLAINBOX_SESSION_SHARE/suspend_30_cycles.log
 _description:
  Automated check of the 30 cycle hibernate log for errors detected by fwts.
 
 plugin: attachment
 id: power-management/suspend-30-cycle-log-attach
 depends: power-management/suspend_30_cycles
-command: [ -e $CHECKBOX_DATA/suspend_30_cycles.log ] && cat $CHECKBOX_DATA/suspend_30_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/suspend_30_cycles.log ] && cat $PLAINBOX_SESSION_SHARE/suspend_30_cycles.log
 _description:
  Attaches the log from the 30 cycle Suspend/Resume test if it exists
 
 plugin: shell
 id: power-management/suspend-30-cycles-time-check
 depends: power-management/suspend_30_cycles
-command: [ -e $CHECKBOX_DATA/suspend_30_cycles_times.log ] && sleep_time_check $CHECKBOX_DATA/suspend_30_cycles_times.log
+command: [ -e $PLAINBOX_SESSION_SHARE/suspend_30_cycles_times.log ] && sleep_time_check $PLAINBOX_SESSION_SHARE/suspend_30_cycles_times.log
 _description:
  Checks the sleep times to ensure that a machine suspends and resumes within a given threshold
 
 plugin: shell
 id: stress/hibernate_250_cycles
 depends: power-management/rtc
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 user: root
 command:
  if type -P fwts >/dev/null; then
   echo "Calling fwts"
-  fwts_test -l $CHECKBOX_DATA/hibernate_250_cycles -s s4 --s4-device-check --s4-device-check-delay=45 --s4-sleep-delay=120 --s4-multiple=250
+  fwts_test -l $PLAINBOX_SESSION_SHARE/hibernate_250_cycles -s s4 --s4-device-check --s4-device-check-delay=45 --s4-sleep-delay=120 --s4-multiple=250
  else
   echo "Calling sleep_test"
-  set -o pipefail; sleep_test -s disk -i 250 -w 120 | tee $CHECKBOX_DATA/hibernate_250_cycles.log
+  set -o pipefail; sleep_test -s disk -i 250 -w 120 | tee $PLAINBOX_SESSION_SHARE/hibernate_250_cycles.log
  fi
 _description:
  PURPOSE:
@@ -100,22 +100,22 @@ _description:
 
 plugin: attachment
 id: stress/hibernate-250-cycle-log-attach
-command: [ -e $CHECKBOX_DATA/hibernate_250_cycles.log ] && cat $CHECKBOX_DATA/hibernate_250_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/hibernate_250_cycles.log ] && cat $PLAINBOX_SESSION_SHARE/hibernate_250_cycles.log
 _description:
  Attaches the log from the 250 cycle Hibernate/Resume test if it exists
 
 plugin: shell
 id: stress/suspend_250_cycles
 depends: power-management/rtc
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 user: root
 command:
  if type -P fwts >/dev/null; then
   echo "Calling fwts"
-  set -o pipefail; fwts_test -l $CHECKBOX_DATA/suspend_250_cycles -s s3 --s3-device-check --s3-device-check-delay=45 --s3-sleep-delay=30 --s3-multiple=250 | tee $CHECKBOX_DATA/suspend_250_cycles_times.log
+  set -o pipefail; fwts_test -l $PLAINBOX_SESSION_SHARE/suspend_250_cycles -s s3 --s3-device-check --s3-device-check-delay=45 --s3-sleep-delay=30 --s3-multiple=250 | tee $PLAINBOX_SESSION_SHARE/suspend_250_cycles_times.log
  else
   echo "Calling sleep_test"
-  set -o pipefail; sleep_test -p -s mem -i 250 | tee $CHECKBOX_DATA/suspend_250_cycles.log
+  set -o pipefail; sleep_test -p -s mem -i 250 | tee $PLAINBOX_SESSION_SHARE/suspend_250_cycles.log
  fi
 _description:
  PURPOSE:
@@ -123,13 +123,13 @@ _description:
 
 plugin: attachment
 id: stress/suspend-250-cycle-log-attach
-command: [ -e $CHECKBOX_DATA/suspend_250_cycles.log ] && cat $CHECKBOX_DATA/suspend_250_cycles.log
+command: [ -e $PLAINBOX_SESSION_SHARE/suspend_250_cycles.log ] && cat $PLAINBOX_SESSION_SHARE/suspend_250_cycles.log
 _description:
  Attaches the log from the 250 cycle Suspend/Resume test if it exists
 
 plugin: shell
 id: stress/suspend-250-cycles-time-check
-command: [ -e $CHECKBOX_DATA/suspend_250_cycles_times.log ] && sleep_time_check $CHECKBOX_DATA/suspend_250_cycles_times.log
+command: [ -e $PLAINBOX_SESSION_SHARE/suspend_250_cycles_times.log ] && sleep_time_check $PLAINBOX_SESSION_SHARE/suspend_250_cycles_times.log
 _description:
  Checks the sleep times to ensure that a machine suspends and resumes within a given threshold
 
@@ -138,64 +138,64 @@ id: stress/reboot
 requires:
  package.name == 'upstart'
  package.name == 'fwts'
-command: pm_test -r 100 --silent --log-level=notset reboot --log-dir=$CHECKBOX_DATA
+command: pm_test -r 100 --silent --log-level=notset reboot --log-dir=$PLAINBOX_SESSION_SHARE
 user: root
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 _description:
  Stress reboot system (100 cycles)
 
 plugin: attachment
 id: stress/reboot_log
 depends: stress/reboot
-command: tar cvfz $CHECKBOX_DATA/stress_reboot.tgz $CHECKBOX_DATA/*reboot.100.log && cat $CHECKBOX_DATA/stress_reboot.tgz
+command: tar cvfz $PLAINBOX_SESSION_SHARE/stress_reboot.tgz $PLAINBOX_SESSION_SHARE/*reboot.100.log && cat $PLAINBOX_SESSION_SHARE/stress_reboot.tgz
 
 plugin: shell
 id: stress/poweroff
 requires:
  package.name == 'upstart'
  package.name == 'fwts'
-command: pm_test -r 100 --silent --log-level=notset poweroff --log-dir=$CHECKBOX_DATA
+command: pm_test -r 100 --silent --log-level=notset poweroff --log-dir=$PLAINBOX_SESSION_SHARE
 user: root
-environ: CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
 _description:
  Stress poweroff system (100 cycles)
 
 plugin: attachment
 id: stress/poweroff_log
 depends: stress/poweroff
-command: tar cvfz $CHECKBOX_DATA/stress_poweroff.tgz $CHECKBOX_DATA/*poweroff.100.log && cat $CHECKBOX_DATA/stress_poweroff.tgz
+command: tar cvfz $PLAINBOX_SESSION_SHARE/stress_poweroff.tgz $PLAINBOX_SESSION_SHARE/*poweroff.100.log && cat $PLAINBOX_SESSION_SHARE/stress_poweroff.tgz
 
 plugin: shell
 id: stress/reboot_check
 depends: stress/reboot
-command: pm_log_check --log-level=notset $CHECKBOX_DATA/pm_test.reboot.100.log $CHECKBOX_DATA/pm_log_check_reboot.100.log
+command: pm_log_check --log-level=notset $PLAINBOX_SESSION_SHARE/pm_test.reboot.100.log $PLAINBOX_SESSION_SHARE/pm_log_check_reboot.100.log
 _description: Check logs for the stress reboot (100 cycles) test case
 
 plugin: attachment
 id: stress/reboot_check_log
 depends: stress/reboot_check
 command:
- tar cvfz $CHECKBOX_DATA/stress_reboot_check.tgz $CHECKBOX_DATA/pm_log_check_reboot.100.log && cat $CHECKBOX_DATA/stress_reboot_check.tgz
+ tar cvfz $PLAINBOX_SESSION_SHARE/stress_reboot_check.tgz $PLAINBOX_SESSION_SHARE/pm_log_check_reboot.100.log && cat $PLAINBOX_SESSION_SHARE/stress_reboot_check.tgz
 
 plugin: shell
 id: stress/poweroff_check
 depends: stress/poweroff
-command: pm_log_check --log-level=notset $CHECKBOX_DATA/pm_test.poweroff.100.log $CHECKBOX_DATA/pm_log_check_poweroff.100.log
+command: pm_log_check --log-level=notset $PLAINBOX_SESSION_SHARE/pm_test.poweroff.100.log $PLAINBOX_SESSION_SHARE/pm_log_check_poweroff.100.log
 _description: Check logs for the stress poweroff (100 cycles) test case
 
 plugin: attachment
 id: stress/poweroff_check_log
 depends: stress/poweroff_check
 command:
- tar cvfz $CHECKBOX_DATA/stress_poweroff_check.tgz $CHECKBOX_DATA/pm_log_check_poweroff.100.log && cat $CHECKBOX_DATA/stress_poweroff_check.tgz
+ tar cvfz $PLAINBOX_SESSION_SHARE/stress_poweroff_check.tgz $PLAINBOX_SESSION_SHARE/pm_log_check_poweroff.100.log && cat $PLAINBOX_SESSION_SHARE/stress_poweroff_check.tgz
 
 plugin: shell
 id: stress/graphics
 requires:
  package.name == 'x11-apps'
 user: root
-environ: CHECKBOX_DATA
-command: graphics_stress_test -b repeat -d -o $CHECKBOX_DATA/graphics-stress-results && echo "Graphics Stress Test completed successfully" || echo "Graphics Stress Test completed, but there are errors. Please see the log $CHECKBOX_DATA/graphics-stress-results for details" && false
+environ: PLAINBOX_SESSION_SHARE
+command: graphics_stress_test -b repeat -d -o $PLAINBOX_SESSION_SHARE/graphics-stress-results && echo "Graphics Stress Test completed successfully" || echo "Graphics Stress Test completed, but there are errors. Please see the log $PLAINBOX_SESSION_SHARE/graphics-stress-results for details" && false
 _description:
  Run the graphics stress test. This test can take a few minutes.
 
@@ -204,7 +204,7 @@ id: stress/graphics-tarball
 requires:
  package.name == 'x11-apps'
 depends: stress/graphics
-command: [ -e $CHECKBOX_DATA/graphics-stress-results ] && tar cvfz $CHECKBOX_DATA/graphics-stress-results.tar.gz $CHECKBOX_DATA/graphics-stress-results
+command: [ -e $PLAINBOX_SESSION_SHARE/graphics-stress-results ] && tar cvfz $PLAINBOX_SESSION_SHARE/graphics-stress-results.tar.gz $PLAINBOX_SESSION_SHARE/graphics-stress-results
 _description: Attaches the graphics stress results to the submission.
 
 plugin: shell
@@ -235,14 +235,14 @@ _description:
 plugin: shell
 id: stress/network_restart
 user: root
-environ: CHECKBOX_DATA
-command: network_restart -t 1 -o $CHECKBOX_DATA
+environ: PLAINBOX_SESSION_SHARE
+command: network_restart -t 1 -o $PLAINBOX_SESSION_SHARE
 _description: Ping ubuntu.com and restart network interfaces 100 times
 
 plugin: attachment
 id: stress/network_restart_log
 depends: stress/network_restart
-command: file=$CHECKBOX_DATA/network_restart.log; if [ -e "$file" ]; then iconv -t 'ascii' -c "$file"; fi
+command: file=$PLAINBOX_SESSION_SHARE/network_restart.log; if [ -e "$file" ]; then iconv -t 'ascii' -c "$file"; fi
 
 plugin: manual
 id: stress/wireless_hotkey
