extract out notebook creation to reused function

diff --git a/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss b/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
--- a/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
+++ b/contrib/checkbox-dss-validation/checkbox-provider-dss/bin/check_dss
@@ -49,22 +49,12 @@ check_dss_has_intel_gpu_acceleration_enabled() {
     fi
 }
 
-check_dss_can_create_itex_215_notebook() {
+check_dss_can_create_notebook() {
     cd "${HOME}"
-    if dss create itex-215-notebook --image=intel/intel-extension-for-tensorflow:2.15.0-xpu-idp-jupyter; then
-        echo "Test success: successfully created an ITEX 2.15 notebook."
+    if dss create "${@}"; then
+        echo "Test success: successfully created notebook with '$*'."
     else
-        >&2 echo "Test failure: failed to create an ITEX 2.15 notebook."
-        exit 1
-    fi
-}
-
-check_dss_can_create_ipex_2120_notebook() {
-    cd "${HOME}"
-    if dss create ipex-2120-notebook --image=intel/intel-extension-for-pytorch:2.1.20-xpu-idp-jupyter; then
-        echo "Test success: successfully created an IPEX 2.1.20 notebook."
-    else
-        >&2 echo "Test failure: failed to create an IPEX 2.1.20 notebook."
+        >&2 echo "Test failure: failed to create notebook with '$*'."
         exit 1
     fi
 }
@@ -76,46 +66,6 @@ check_dss_has_nvidia_gpu_acceleration_enabled() {
         echo "Test success: 'dss status' correctly reports NVIDIA GPU status."
     else
         >&2 echo "Test failure: 'dss status' does not report that NVIDIA GPU acceleration is enabled."
-        exit 1
-    fi
-}
-
-check_dss_can_create_pytorch_cuda_notebook() {
-    cd "${HOME}"
-    if dss create pytorch-cuda --image=pytorch-cuda; then
-        echo "Test success: successfully created pytorch-cuda notebook."
-    else
-        >&2 echo "Test failure: failed to create pytorch-cuda notebook."
-        exit 1
-    fi
-}
-
-check_dss_can_create_tensorflow_cuda_notebook() {
-    cd "${HOME}"
-    if dss create tensorflow-cuda --image=tensorflow-cuda; then
-        echo "Test success: successfully created tensorflow-cuda notebook."
-    else
-        >&2 echo "Test failure: failed to create tensorflow-cuda notebook."
-        exit 1
-    fi
-}
-
-check_dss_can_create_pytorch_cpu_notebook() {
-    cd "${HOME}"
-    if dss create pytorch-cpu --image=pytorch; then
-        echo "Test success: successfully created pytorch-cpu notebook."
-    else
-        >&2 echo "Test failure: failed to create pytorch-cpu notebook."
-        exit 1
-    fi
-}
-
-check_dss_can_create_tensorflow_cpu_notebook() {
-    cd "${HOME}"
-    if dss create tensorflow-cpu --image=tensorflow; then
-        echo "Test success: successfully created tensorflow-cpu notebook."
-    else
-        >&2 echo "Test failure: failed to create tensorflow-cpu notebook."
         exit 1
     fi
 }
@@ -139,13 +89,7 @@ help_function() {
     echo -e "\t<dss_namespace_is_deployed>: check_dss_namespace_is_deployed"
     echo -e "\t<mlflow_status_is_ready>: check_mlflow_status_is_ready"
     echo -e "\t<intel_gpu_acceleration_is_enabled>: check_dss_has_intel_gpu_acceleration_enabled"
-    echo -e "\t<can_create_itex_215_notebook>: check_dss_can_create_itex_215_notebook"
-    echo -e "\t<can_create_ipex_2120_notebook>: check_dss_can_create_ipex_2120_notebook"
     echo -e "\t<nvidia_gpu_acceleration_is_enabled>: check_dss_has_nvidia_gpu_acceleration_enabled"
-    echo -e "\t<can_create_pytorch_cuda_notebook>: check_dss_can_create_pytorch_cuda_notebook"
-    echo -e "\t<can_create_tensorflow_cuda_notebook>: check_dss_can_create_tensorflow_cuda_notebook"
-    echo -e "\t<can_create_pytorch_cpu_notebook>: check_dss_can_create_pytorch_cpu_notebook"
-    echo -e "\t<can_create_tensorflow_cpu_notebook>: check_dss_can_create_tensorflow_cpu_notebook"
     echo -e "\t<can_remove_notebook>: check_dss_can_remove_notebook <notebook_name>"
 }
 
@@ -155,13 +99,8 @@ main() {
     dss_namespace_is_deployed) check_dss_namespace_is_deployed ;;
     mlflow_status_is_ready) check_mlflow_status_is_ready ;;
     intel_gpu_acceleration_is_enabled) check_dss_has_intel_gpu_acceleration_enabled ;;
-    can_create_itex_215_notebook) check_dss_can_create_itex_215_notebook ;;
-    can_create_ipex_2120_notebook) check_dss_can_create_ipex_2120_notebook ;;
     nvidia_gpu_acceleration_is_enabled) check_dss_has_nvidia_gpu_acceleration_enabled ;;
-    can_create_pytorch_cuda_notebook) check_dss_can_create_pytorch_cuda_notebook ;;
-    can_create_tensorflow_cuda_notebook) check_dss_can_create_tensorflow_cuda_notebook ;;
-    can_create_pytorch_cpu_notebook) check_dss_can_create_pytorch_cpu_notebook ;;
-    can_create_tensorflow_cpu_notebook) check_dss_can_create_tensorflow_cpu_notebook ;;
+    can_create_notebook) check_dss_can_create_notebook "${@:2}" ;;
     can_remove_notebook) check_dss_can_remove_notebook "${@:2}" ;;
     *) help_function ;;
     esac
