Use launcher and cert-tools in Testflinger job for testing DSS (New) (#1947)
* Temporarily reduce test matrix while developing

* Trigger snap build and download atrifact

* Add step to find the downloaded snap

* Refactor step to build job.yaml from template

* Accept built snap in testflinger job-def.yaml

* Use attached pre-built snap in testflinger job

* Temp disable submitting job to testflinger

* Remove unused BRANCH env variable

* Set path to download artifact in working directory

* Make DSS and microk8s channels inputs

* Add summary to each queue in matrix

* Update image url for dell-precision-5680 queue

* Re-enable all queues in the matrix

* Add the default launcher for checkbox-dss

* Use launcher in testflinger job

* Remove validate-with-gpu from checkbox-dss snap

* Fix some misspellings in snapcraft.yaml

* Migrate testflinger job to use cert tools

* Re-enable submitting job to testflinger

* Fix path to built job.yaml

* Remove awaiting rollout of outdated daemonset

* Allow SSH to be degraded

I had seen this in the generic_source.yaml, but wanted to see if I could
get away without it.  Unfortunately, some devices do seem to need this,
and we need to try if allowing degraded SSH to let the tests proceed
actually have a bad impact or not.

* Wait for snap changes after each snap install

* Add running snap refresh

* Increase sleep time before checking rollout

* Switch from using sed to envsubst to fill template

* Fix typo in calling envsubst

* Switch to ENV_ from REPLACE_ for template params

diff --git a/contrib/checkbox-dss-validation/testflinger/job-def.yaml b/contrib/checkbox-dss-validation/testflinger/job-def.yaml
--- a/contrib/checkbox-dss-validation/testflinger/job-def.yaml
+++ b/contrib/checkbox-dss-validation/testflinger/job-def.yaml
@@ -1,38 +1,69 @@
-job_queue: $REPLACE_QUEUE
+job_queue: $ENV_QUEUE
 output_timeout: 1800
 provision_data:
-  $REPLACE_PROVISION_DATA
+  $ENV_PROVISION_DATA
 test_data:
   attachments:
-    - local: $REPLACE_CB_DSS_SNAP
+    - local: $ENV_CB_DSS_SNAP
+    - local: $ENV_LAUNCHER
   test_cmds: |
 
     # Exit immediately if a test fails
     set -e
 
-    scp attachments/test/$REPLACE_CB_DSS_SNAP ubuntu@$DEVICE_IP:
+    # Constants
+    CHECKBOX_RUNTIME="checkbox22"
+    RESOURCES_PATH="attachments/test"
+    TOOLS_PATH=tools
 
-    # Initial setup
-    ssh -t ubuntu@$DEVICE_IP '
-      export DEBIAN_FRONTEND=noninteractive
-      export NEEDRESTART_MODE=a
-      sudo -E apt update
-      sudo -E apt -y upgrade
-      sudo -E apt -y install git
-    '
+    # Retrieve cert-tools
+    curl -Ls -o install_tools.sh https://raw.githubusercontent.com/canonical/certification-lab-ci-tools/main/install_tools.sh
+    source install_tools.sh $TOOLS_PATH --branch main
 
-    # Install dependencies
-    ssh -t ubuntu@$DEVICE_IP '
-      sudo snap install checkbox22
-      sudo snap install --dangerous --classic ./$REPLACE_CB_DSS_SNAP
-    '
+    wait_for_ssh --allow-degraded
+    _run clean_machine --im-sure
 
-    # Install test dependencies
-    ssh -t ubuntu@$DEVICE_IP '
-      checkbox-dss.install-deps --dss-snap-channel $REPLACE_DSS_CHANNEL --microk8s-snap-channel $REPLACE_MICROK8S_CHANNEL
-    '
+    _run install_packages git
+    wait_for_ssh --allow-degraded
 
-    # Run tests
-    ssh -t ubuntu@$DEVICE_IP '
-      checkbox-dss.validate-with-gpu
-    '
+    # Refresh snaps
+    _run sudo snap refresh --no-wait
+    wait_for_snap_changes
+
+    # Install runtime and provider on device
+    echo "Installing checkbox runtime on device (from snap)"
+    _run sudo snap install $CHECKBOX_RUNTIME --no-wait
+    wait_for_snap_changes
+
+    echo "Installing checkbox-dss snap from attachment"
+    _put $RESOURCES_PATH/$ENV_CB_DSS_SNAP :
+    _run sudo snap install --dangerous --classic ./$ENV_CB_DSS_SNAP --no-wait
+    wait_for_snap_changes
+
+    echo "Available snaps on device"
+    _run sudo snap list
+
+    # Restart the checkbox service just in case
+    _run sudo systemctl restart snap.checkbox-dss.remote-slave.service
+    check_for_checkbox_service --debug || exit 1
+
+    # Sync Checkbox version between agent and device
+    CHECKBOX_VERSION=$(_run checkbox-dss.checkbox-cli --version)
+    [ -z "$CHECKBOX_VERSION" ] && echo "Error: Unable to retrieve Checkbox version from device" && exit 1
+    echo "Installing checkbox $CHECKBOX_VERSION on agent container from source"
+    install_checkbox_agent_source $CHECKBOX_VERSION $TOOLS_PATH
+
+    # Install dependencies on device for running checkbox-dss tests
+    # XXX:@motjuste: to be moved to Checkbox setup phase
+    _run wait_for_packages_complete
+    _run checkbox-dss.install-deps --dss-snap-channel $ENV_DSS_CHANNEL --microk8s-snap-channel $ENV_MICROK8S_CHANNEL
+    _run wait_for_packages_complete
+    wait_for_ssh --allow-degraded
+
+    # run the test plan
+    PYTHONUNBUFFERED=1 checkbox-cli control $DEVICE_IP $RESOURCES_PATH/$ENV_LAUNCHER
+    EXITCODE=$?
+
+    # XXX:@motjuste: gather artifacts
+
+    exit $EXITCODE
