Remove i386 builds from the workflows (infra) (#791)
Remove i386 builds from the workflows

diff --git a/.github/workflows/checkbox-core-snap-beta-release.yml b/.github/workflows/checkbox-core-snap-beta-release.yml
--- a/.github/workflows/checkbox-core-snap-beta-release.yml
+++ b/.github/workflows/checkbox-core-snap-beta-release.yml
@@ -38,7 +38,7 @@ jobs:
         with:
           path: checkbox-core-snap/series${{ matrix.releases }}
           snapcraft-channel: 7.x/stable
-          snapcraft-args: remote-build --build-on amd64,arm64,armhf,i386 --launchpad-accept-public-upload
+          snapcraft-args: remote-build --build-on amd64,arm64,armhf --launchpad-accept-public-upload
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
@@ -54,21 +54,10 @@ jobs:
       - name: Check that snapcraft built the expected amount of snaps
         run: |
           NB_SNAPS=$(find checkbox-core-snap/series${{ matrix.releases }} -maxdepth 1 -type f -name *.snap | wc -l)
-          # Expecting 3 snaps for checkbox20 and checkbox22 (amd64, armhf, arm64)
-          # and 4 snaps for checkbox16 and checkbox18 (i386, amd64, armhf, arm64)
-          if [ ${{ matrix.releases }} == "16" ] || [ ${{ matrix.releases }} == "18" ]
+          if [ ${NB_SNAPS} != "3" ]
           then
-            if [ ${NB_SNAPS} != "4" ]
-            then
-              echo "Error: Snapcraft should have produced 4 snaps, found ${NB_SNAPS} instead."
-                exit 1
-            fi
-          else
-            if [ ${NB_SNAPS} != "3" ]
-            then
-              echo "Error: Snapcraft should have produced 3 snaps, found ${NB_SNAPS} instead."
-              exit 1
-            fi
+            echo "Error: Snapcraft should have produced 3 snaps, found ${NB_SNAPS} instead."
+            exit 1
           fi
       - name: Upload checkbox core snaps to the store
         run: |
diff --git a/.github/workflows/checkbox-snap-beta-release.yml b/.github/workflows/checkbox-snap-beta-release.yml
--- a/.github/workflows/checkbox-snap-beta-release.yml
+++ b/.github/workflows/checkbox-snap-beta-release.yml
@@ -39,7 +39,7 @@ jobs:
         with:
           path: checkbox-snap/series_${{ matrix.type }}${{ matrix.releases }}
           snapcraft-channel: 7.x/stable
-          snapcraft-args: remote-build --build-on amd64,arm64,armhf,i386 --launchpad-accept-public-upload
+          snapcraft-args: remote-build --build-on amd64,arm64,armhf --launchpad-accept-public-upload
       - uses: actions/upload-artifact@v3
         if: failure()
         with:
@@ -55,21 +55,10 @@ jobs:
       - name: Check that snapcraft built the expected amount of snaps
         run: |
           NB_SNAPS=$(find checkbox-snap/series_${{ matrix.type }}${{ matrix.releases }} -maxdepth 1 -type f -name *.snap | wc -l)
-          # Expecting 3 snaps for 20 and 22 releases (amd64, armhf, arm64)
-          # and 4 snaps for 16 and 18 releases (i386, amd64, armhf, arm64)
-          if [ ${{ matrix.releases }} == "16" ] || [ ${{ matrix.releases }} == "18" ]
+          if [ ${NB_SNAPS} != "3" ]
           then
-            if [ ${NB_SNAPS} != "4" ]
-            then
-              echo "Error: Snapcraft should have produced 4 snaps, found ${NB_SNAPS} instead."
-                exit 1
-            fi
-          else
-            if [ ${NB_SNAPS} != "3" ]
-            then
-              echo "Error: Snapcraft should have produced 3 snaps, found ${NB_SNAPS} instead."
-              exit 1
-            fi
+            echo "Error: Snapcraft should have produced 3 snaps, found ${NB_SNAPS} instead."
+            exit 1
           fi
       - name: Upload checkbox snaps to the store
         run: |
