Fix the metabox trigger so that it is run to completion

diff --git a/.github/workflows/metabox.yaml b/.github/workflows/metabox.yaml
--- a/.github/workflows/metabox.yaml
+++ b/.github/workflows/metabox.yaml
@@ -10,16 +10,19 @@ jobs:
   metabox_run_required:
     runs-on: ubuntu-latest
     name: Check for changes in metabox and checkbox-ng dirs
+    outputs:
+      required_run: ${{ steps.check_diff.outputs.required_run }}
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
       - name: Use git diff to see if there are any changes in the metabox and checkbox-ng directories
         id: check_diff
-        continue-on-error: true
         run: |
-          git diff --exit-code HEAD origin/main -- checkbox-ng metabox
-          if [[ $? -eq 0 ]]
+          # catch the return code in subshell to avoid github stopping the job 
+          # due to it being non-0, non-0 means: "found some diff"
+          SHOULD=$(git diff --exit-code HEAD origin/main -- checkbox-ng metabox 1>/dev/null 2>/dev/null; echo $?)
+          if [[ $SHOULD -eq 0 ]]
             then
               echo "No Metabox run required."
               echo "required_run=false" >> $GITHUB_OUTPUT
@@ -29,7 +32,7 @@ jobs:
           fi
 
   Metabox:
-    if: (github.event.review.state == 'approved' && needs.metabox_run_required.outputs.required_run == 'true') || github.event_name == 'workflow_dispatch'
+    if: (github.event.review.state == 'approved' && true == fromJSON(needs.metabox_run_required.outputs.required_run)) || github.event_name == 'workflow_dispatch'
     strategy:
       fail-fast: false
       matrix:
