Better output for the test job and compulsory brackets
Minor: removed grep output

diff --git a/.github/workflows/pr_validation.yaml b/.github/workflows/pr_validation.yaml
--- a/.github/workflows/pr_validation.yaml
+++ b/.github/workflows/pr_validation.yaml
@@ -14,4 +14,15 @@ jobs:
     - name: Checking the presence of the Traceability Marker in the PR title
       env:
         PR_TITLE: ${{ github.event.pull_request.title }}
-      run: echo "$PR_TITLE" | grep -iP "(infra|bugfix|new|breaking)\)?$"
+      run: |
+        if echo "$PR_TITLE" | grep -iqP "\((infra|bugfix|new|breaking)\)$"; then
+          echo "PR title contains the traceability marker"
+          exit 0
+        else
+          echo "Traceability marker missing"
+          echo "Update your title with one of the following postfix"
+          echo "(Infra,Bugfix,New,Breaking)"
+          echo
+          echo "e.g. $PR_TITLE (BugFix)"
+          exit 1
+        fi
